controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Chapter;
use app\models\Contents;
use app\models\Essay;
use app\models\History;
use app\models\LoginForm;
use app\models\Magazine;
use app\models\MagazineSearch;
use app\models\User;
use Exception;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

// use yii\web\Cookie;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id == 'error') $this->layout = 'index';
            return true;
        } else {
            return false;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'layout' => 'index',
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex($barcode = null, $search = null)
    {
        if (isset($barcode) && strlen($barcode) == 9) {
            return $this->redirect(['essay/view', 'id' => $barcode]);
        } else if (isset($search) && strlen($search) > 0) {
            return $this->redirect(['site/search', 'search' => $search]);
        }
        if (Yii::$app->user->isGuest) return $this->redirect(['site/login']);
        $models = Essay::find()->where('deleted=0')->all();
        return $this->render('index', [
            'models' => $models
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        // $cookie = Yii::$app->request->cookies;
        // if ($cookie->has('username'))
        //     $model->username = $cookie->get('username');

        if ($model->load(Yii::$app->request->post())) {
            $user = User::find()
                ->where([
                    'username' => $model->username,
                    'password' => $model->password,
                    'deleted' => 0
                ])->one();
            if (isset($user)) {
                if ($model->rememberMe) {
                    Yii::$app->user->login(@$user, 3600 * 24 * 30);
                    // $cookie->add(
                    //     new Cookie([
                    //         'name' => 'username',
                    //         'value' => $user->username,
                    //         'expire' => time() + 3600 * 24 * 30 //1 month
                    //     ])
                    // );
                }
                return $this->redirect(['site/index']);
            }
            Yii::$app->session->setFlash('danger', 'ຊື່ຜູ້ໃຊ້ ຫຼື ລະຫັດຜ່ານ ບໍ່ຖືກຕ້ອງ');
            return $this->redirect(['site/login']);
        }
        $this->view->title = "ເຂົ້າສູ່ລະບົບ";
        $model->password = '';
        $this->layout = 'login';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionUpdate()
    {
        try {
            //            $this->exe("cd ../");
            $this->exe("yii migrate");
            //            $this->exe("git pull");
        } catch (Exception $ex) {
            print_r($ex);
        }
    }

    private function exe($command)
    {
        $return = [];
        $out = [];
        echo "exe " . $command;
        exec($command, $out, $return);
        print_r($out);
        echo "\r\n";
        print_r($return);
    }

    public function actionFix()
    {
        $models = Essay::find()->where('deleted=0')->all();
        foreach ($models as $model) {
            $hitory = History::find()
                ->where([
                    'essay_id' => $model->id
                ])
                ->andWhere("lower(sr) <> 'u' ")
                ->orderBy('created_date desc')
                ->one();
            if (isset($hitory)) {
                try {
                    $model->status_id = $hitory->status_id;
                    $model->employee_id = $hitory->employee_id;
                    if (!$model->save()) {
                        throw new \yii\db\Exception($model->errors);
                    }
                    echo json_encode($model->attributes);
                    echo "<hr/>";
                } catch (Exception $exception) {
                    print_r($exception);
                }
            }
        }
    }

    public function actionIndexx()
    {
        $this->layout = 'index';
        $chapters = Chapter::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->orderBy('id desc')
            ->all();
        $mags = Magazine::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->andWhere('date(current_timestamp) >= from_date')
            ->orderBy('id desc')
            ->all();

        $searchModel = new MagazineSearch();
        $searchModel->deleted = 0;
        $magDataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $magDataProvider->query->orderBy('id desc');

        return $this->render('indexx', [
            'chapters' => $chapters,
            'magazines' => $mags,
            'magDataProvider' => $magDataProvider
        ]);
    }

    public function actionChapterView($id)
    {
        $this->layout = 'index';
        $model = Chapter::find()->where(['id' => $id, 'deleted' => 0, 'hidden' => 0])->one();
        if (!isset($model)) {
            return $this->redirect(['site/error']);
        }
        $chapters = Chapter::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->orderBy('id desc')
            ->all();
        return $this->render('chapter-view', [
            'model' => $model,
            'chapters' => $chapters,
        ]);
    }

    public function actionMagazineView($id)
    {
        $this->layout = 'index';
        $model = Magazine::find()->where(['id' => $id])->one();
        if (!isset($model)) {
            return $this->redirect(['site/error']);
        }
        $chapters = Chapter::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->orderBy('id desc')
            ->all();
        return $this->render('magazine-view', [
            'model' => $model,
            'chapters' => $chapters,
        ]);
    }

    public function actionChapters()
    {
        $this->layout = 'index';
        $query = Chapter::find()->where(['deleted' => 0, 'hidden' => 0]);
        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        $mags = Magazine::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])            
            ->andWhere('date(current_timestamp) >= from_date')
            ->orderBy('id desc')
            ->all();
        return $this->render('chapters', [
            'provider' => $provider,
            'magazines' => $mags,
            'models' => [],
        ]);
    }

    public function actionMagazines()
    {
        $this->layout = 'index';
        $query = Magazine::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->andWhere('date(current_timestamp) >= from_date');
        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        $chapters = Chapter::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0
            ])
            ->orderBy('id desc')
            ->all();
        return $this->render('magazines', [
            'provider' => $provider,
            'chapters' => $chapters,
            'models' => [],
        ]);
    }

    public function actionContent($code)
    {
        $this->layout = 'index';
        $content = Contents::find()->where(['code' => $code])->one();
        return $this->render('content', [
            'content' => $content,
        ]);
    }

    public function actionSearch($search = null)
    {
        $this->layout = 'index';
        $providerMags = null;
        $providerChapters = null;

        $chapters = Chapter::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0,
            ])
            ->limit(3)
            ->orderBy('id desc')
            ->all();

        $mags = Magazine::find()
            ->where([
                'deleted' => 0,
                'hidden' => 0,
            ])
            ->limit(3)
            ->orderBy('id desc')
            ->all();

        if (isset($search)) {
            $queryMags = Magazine::find()
                ->where([
                    'deleted' => 0,
                    'hidden' => 0
                ])                
                ->andWhere('date(current_timestamp) >= from_date')

views/site/_chapter.php
<?php

use yii\helpers\Html;
?>
<div style="border-bottom: 1px solid #eeeeee;padding-top: 1em">
    <div style="font-size: 1.3em">
        <?= Html::a($model->title, ['site/chapter-view', 'id' => $model->id], []) ?>
    </div>
    <div style="padding-top: 0.5em;color: #999999;padding-bottom: 0.5em">
        <i class="glyphicon glyphicon-pencil" style="font-size: 0.7em;"></i>
        <?= $model->author ?>
    </div>
</div>

views/site/_magazine.php
<?php

use yii\helpers\Html;
?>
<div style="border-bottom: 1px solid #eeeeee;padding-top: 1em">
    <div class="row">
        <div class="col-sm-2">
                <?= Html::a(Html::img($model->cover_image, ['style' => [
                    'width' => '100px'
                ]]), ['site/magazine-view', 'id' => $model->id], []) ?>
        </div>
        <div class="col-sm-10">
            <div style="font-size: 1.3em">
                <?= Html::a($model->title, ['site/magazine-view', 'id' => $model->id], []) ?>
            </div>
            <div style="padding-top: 0.5em;color: #999999;padding-bottom: 0.5em">
                <i class="glyphicon glyphicon-pencil" style="font-size: 0.7em;"></i>
                <?= $model->author ?>
            </div>
        </div>
    </div>
</div>

views/site/chapter-view.php
<?php

use yii\helpers\Html;

?>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php

                foreach ($chapters as $key => $chapter) : ?>
                    <div style="border-bottom: 1px solid #eeeeee;padding-top: 1em">
                        <div style="font-size: 1.3em">
                            <?= Html::a($chapter->title, ['site/chapter-view', 'id' => $chapter->id], []) ?>
                        </div>
                        <div style="padding-top: 0.5em;color: #999999;padding-bottom: 0.5em">
                            <i class="glyphicon glyphicon-pencil" style="font-size: 0.7em;"></i>
                            <?= $chapter->author ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>
        </div>
        <div class="col-sm-9">
            <div>
                <h1 class="text-center"><?= $model->title ?></h1>
                <div class="text-center">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <?= $model->author ?>
                </div>
            </div>
            <div style="padding: 2em 4em 8em 4em">
                <hr style="border-bottom: 5px solid #ff0000">
                <?= $model->content ?>

                <hr style="border-bottom: 5px solid #ff0000">
            </div>
        </div>
    </div>
</div>

views/site/chaptertype.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

?>
<div class="container">
    <div class="row">
        <div class="col-sm-10">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ ປະເພດ "<?= $category->name ?>"
                </span>
            </div>
            <div style="margin-top: 1em">
                <?php
                echo ListView::widget([
                    'dataProvider' => $providerChapters,
                    'itemView' => '_chapter',
                    'summary' => false,
                    'emptyText' => 'ບໍ່ມີຂໍ້ມູນ',
                ]);
                ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php
                if (isset($chapters)) :
                    foreach ($chapters as $key => $chapter) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 1em;">
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($chapter->title, ['site/chapter-view', 'id' => $chapter->id], [
                                    'class' => 'text-left'
                                ]) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>

            <hr>

            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານ
                </span>
            </div>
            <div>
                <?php
                if (isset($magazines)) :
                    foreach ($magazines as $key => $magazine) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 2em">
                            <div style="padding: 0 auto;">
                                <?= Html::a(Html::img($magazine->cover_image, ['style' => ['width' => '100%']]), ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($magazine->title, ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/magazines'], []) ?>
            </div>
        </div>
    </div>
</div>

views/site/content.php
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <?= isset($content) ? $content->content : '' ?>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

$this->title = 'ພົບບັນຫາ';
?>
<div class="site-error">
  <div class="alert alert-danger">
    ບໍ່ພົບຂໍ້ມູນ
    <p>
        <?= $name ?>
    </p>
  </div>
</div>

views/site/history.php
ຄວາມເປັນມາ

views/site/indexx.php
<?php

use yii\helpers\Html;
?>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php foreach ($chapters as $key => $chapter) : ?>
                    <div style="border-bottom: 1px solid #eeeeee;padding-top: 1em">
                        <div style="font-size: 1.3em">
                            <?= Html::a($chapter->title, ['site/chapter-view', 'id' => $chapter->id], []) ?>
                        </div>
                        <div style="padding-top: 0.5em;color: #999999;padding-bottom: 0.5em">
                            <i class="glyphicon glyphicon-pencil" style="font-size: 0.7em;"></i>
                            <?= $chapter->author ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>
        </div>
        <div class="col-sm-7">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <?php foreach ($magazines as $key => $mag) : ?>
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="<?= $key == 0 ? 'active' : '' ?>"></li>                    
                    <?php endforeach; ?>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <?php foreach ($magazines as $key => $mag) : ?>
                        <div class="text-center item <?= $key == 0 ? 'active' : '' ?>">
                            <?= Html::img($mag->cover_image, ['style' => [
                                'height' => '400px',
                                'margin' => '0 auto'
                            ]]) ?>

                            <div class="carousel-caption">
                                <?php // echo $mag->title 
                                ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div style="font-size: 1.5em;margin-top: 1em; margin-bottom: 1em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານປະຈຸບັນ
                </span>
            </div>
            <div>
                <?php foreach ($magazines as $key => $mag) : ?>
                    <div class="row" style="border-bottom: 1px solid #eeeeee;margin: 1em">
                        <div class="col-sm-2">
                            <?= Html::a(Html::img($mag->cover_image, ['style' => [
                                'width' => '100px',
                            ]]), ['site/magazine-view', 'id' => $mag->id], []) ?>
                        </div>
                        <div class="col-sm-10" style="font-size: 1.2em;">
                            <strong>
                                <?= Html::a($mag->title, ['site/magazine-view', 'id' => $mag->id], []) ?>
                                <?= $mag->subtitle ?>
                            </strong>
                            <div style="color: #999999;">
                                <small>
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    <?= $mag->author ?>
                                </small>
                            </div>
                            <div class="text-right" style="padding-top: 2em">
                                <i>
                                    <small>
                                        <i class="glyphicon glyphicon-calendar"></i>
                                        <?php
                                        $date = new DateTime($mag->created_date);
                                        echo $date->format('d/m/Y');
                                        ?>
                                    </small>
                                </i>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານ
                </span>
            </div>
            <div>
                <?php
                if (isset($magazines)) :
                    foreach ($magazines as $key => $magazine) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 2em">
                            <div style="padding: 0 2em;">
                                <?= Html::a(Html::img($magazine->cover_image, [
                                    'style' => ['width' => '100px']
                                ]), ['site/magazine-view', 'id' => $mag->id], []) ?>
                            </div>
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($magazine->title, ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/magazines'], []) ?>
            </div>
        </div>
    </div>

    <hr style="margin-top: 2em;">
    <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
        <span style="border-bottom: 5px solid #ff0000;">
            ວາລະສານແຕ່ລະເດືອນ
        </span>
    </div>
    <div class="row">
        <?php
        foreach ($magazines as $key => $mag) : ?>
            <div class="col-sm-1">
                <?= Html::a(Html::img($mag->cover_image, [
                    'style' => [
                        'width' => '100%'
                    ]
                ]), ['site/magazine-view', 'id' => $mag->id]) ?>
                <div class="text-center" style="font-size: 1.2em;">
                    <?= Html::a("ເດືອນ ". $mag->for_month ." ປີ " . $mag->for_year, ['site/magazine-view', 'id' => $mag->id]) ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

views/site/magazines.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

?>
<div class="container">
    <div class="row">
        <div class="col-sm-10">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານແຕ່ລະເດືອນ
                </span>
            </div>
            <div style="margin-top: 1em">
                <?php
                echo ListView::widget([
                    'dataProvider' => $provider,
                    'itemView' => '_magazine',
                    'summary' => false,
                    'emptyText' => 'ບໍ່ມີຂໍ້ມູນ',
                ]);
                ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php
                if (isset($chapters)) :
                    foreach ($chapters as $key => $chapter) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 1em;">
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($chapter->title, ['site/chapter-view', 'id' => $chapter->id], [
                                    'class' => 'text-left'
                                ]) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>
        </div>
    </div>
</div>

views/site/org.php
ຄະນະບັນນາທິການ

views/site/search.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

?>
<div class="container">
    <div class="row">
        <div class="col-sm-10">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ ທີ່ກ່ຽວຂ້ອງກັບ "<?= $search ?>"
                </span>
            </div>
            <div style="margin-top: 1em">
                <?php
                echo ListView::widget([
                    'dataProvider' => $providerChapters,
                    'itemView' => '_chapter',
                    'summary' => false,
                    'emptyText' => 'ບໍ່ມີຂໍ້ມູນ',
                ]);
                ?>
            </div>
            <div style="height: 50px;"></div>
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານ ທີ່ກ່ຽວຂ້ອງກັບ "<?= $search ?>"
                </span>
            </div>
            <div style="margin-top: 1em">
                <?php
                echo ListView::widget([
                    'dataProvider' => $providerMags,
                    'itemView' => '_magazine',
                    'summary' => false,
                    'emptyText' => 'ບໍ່ມີຂໍ້ມູນ',
                ]);
                ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php
                if (isset($chapters)) :
                    foreach ($chapters as $key => $chapter) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 1em;">
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($chapter->title, ['site/chapter-view', 'id' => $chapter->id], [
                                    'class' => 'text-left'
                                ]) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>

            <hr>

            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ວາລະສານ
                </span>
            </div>
            <div>
                <?php
                if (isset($magazines)) :
                    foreach ($magazines as $key => $magazine) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 2em">
                            <div style="padding: 0 auto;">
                                <?= Html::a(Html::img($magazine->cover_image, ['style' => ['width' => '100%']]), ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($magazine->title, ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/magazines'], []) ?>
            </div>
        </div>
    </div>
</div>

views/site/searchnotfound.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

?>
<div class="container">
    <div class="row">
        <div class="col-sm-10">
            ບໍ່ພົບຂໍ້ມູນ
        </div>
        <div class="col-sm-2">
            <div style="font-size: 1.5em;border-bottom: 1px solid #ff0000;margin-bottom: 1em">
                <span style="border-bottom: 5px solid #ff0000;">
                    ບົດນຳ
                </span>
            </div>
            <div>
                <?php
                if (isset($magazines)) :
                    foreach ($magazines as $key => $magazine) : ?>
                        <div style="border-bottom: 1px solid #eeeeee; padding-bottom: 2em">
                            <div style="padding: 0 auto;">
                                <?= Html::a(Html::img($magazine->cover_image, ['style' => ['width' => '100%']]), ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                            <div class="text-center" style="font-size: 1.2em;">
                                <?= Html::a($magazine->title, ['site/magazine-view', 'id' => $magazine->id], []) ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>

            <div style="margin-top: 1em" class="text-right">
                <?= Html::a('ເບິ່ງທັງໝົດ >>', ['site/chapters'], []) ?>
            </div>
        </div>
    </div>
</div>